import type { CurrentUser } from "./auth";
import type { RoleKey } from "./enums";

// Permission keys used across the app. Format: <resource>.<action>[.<qualifier>]
export const PERMISSIONS = {
  // change orders
  CO_VIEW: "change_order.view",
  CO_CREATE: "change_order.create",
  CO_EDIT: "change_order.edit",
  CO_SUBMIT: "change_order.submit",
  CO_APPROVE_CAPTAIN: "change_order.approve.captain",
  CO_APPROVE_OWNERS_REP: "change_order.approve.owners_rep",
  CO_APPROVE_YARD: "change_order.approve.yard",
  CO_APPROVE_FINANCE: "change_order.approve.finance",
  CO_APPROVE_TECH: "change_order.approve.tech_manager",
  CO_APPROVE_CLASS: "change_order.approve.class",
  CO_APPROVE_FLAG: "change_order.approve.flag",
  CO_CANCEL: "change_order.cancel",
  // crew requests
  CR_VIEW: "crew_request.view",
  CR_CREATE: "crew_request.create",
  CR_TRIAGE: "crew_request.triage",
  CR_ASSIGN: "crew_request.assign",
  CR_COMPLETE: "crew_request.complete",
  // financials
  FIN_VIEW: "financial.view",
  FIN_EDIT_BUDGET: "financial.budget.edit",
  FIN_APPROVE: "financial.approve",
  // schedule
  SCH_VIEW: "schedule.view",
  SCH_EDIT: "schedule.edit",
  // logistics
  LOG_VIEW: "logistics.view",
  LOG_EDIT: "logistics.edit",
  // inventory
  INV_VIEW: "inventory.view",
  INV_EDIT: "inventory.edit",
  // drawings
  DRW_VIEW: "drawing.view",
  DRW_UPLOAD: "drawing.upload",
  DRW_APPROVE: "drawing.approve",
  // documents
  DOC_VIEW: "document.view",
  DOC_UPLOAD: "document.upload",
  DOC_VIEW_CONFIDENTIAL: "document.view.confidential",
  // contractors
  CON_VIEW: "contractor.view",
  CON_EDIT: "contractor.edit",
  // meetings
  MTG_VIEW: "meeting.view",
  MTG_EDIT: "meeting.edit",
  // risks
  RSK_VIEW: "risk.view",
  RSK_EDIT: "risk.edit",
  // admin
  ADM_USERS: "admin.users",
  ADM_ROLES: "admin.roles",
  ADM_SETTINGS: "admin.settings",
  AUDIT_VIEW: "audit.view",
  EXPORT: "export",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Role -> default permission set. Keep this single matrix as the seed.
export const ROLE_PERMISSIONS: Record<RoleKey, PermissionKey[]> = {
  OWNER: [
    PERMISSIONS.CO_VIEW, PERMISSIONS.CR_VIEW, PERMISSIONS.FIN_VIEW,
    PERMISSIONS.SCH_VIEW, PERMISSIONS.LOG_VIEW, PERMISSIONS.INV_VIEW,
    PERMISSIONS.DRW_VIEW, PERMISSIONS.DOC_VIEW, PERMISSIONS.DOC_VIEW_CONFIDENTIAL,
    PERMISSIONS.CON_VIEW, PERMISSIONS.MTG_VIEW, PERMISSIONS.RSK_VIEW,
    PERMISSIONS.AUDIT_VIEW, PERMISSIONS.EXPORT,
  ],
  OWNERS_REP: [
    PERMISSIONS.CO_VIEW, PERMISSIONS.CO_CREATE, PERMISSIONS.CO_EDIT, PERMISSIONS.CO_SUBMIT,
    PERMISSIONS.CO_APPROVE_OWNERS_REP, PERMISSIONS.CO_CANCEL,
    PERMISSIONS.CR_VIEW, PERMISSIONS.CR_TRIAGE, PERMISSIONS.CR_ASSIGN,
    PERMISSIONS.FIN_VIEW, PERMISSIONS.FIN_APPROVE,
    PERMISSIONS.SCH_VIEW, PERMISSIONS.SCH_EDIT,
    PERMISSIONS.LOG_VIEW, PERMISSIONS.LOG_EDIT,
    PERMISSIONS.INV_VIEW, PERMISSIONS.DRW_VIEW, PERMISSIONS.DRW_APPROVE,
    PERMISSIONS.DOC_VIEW, PERMISSIONS.DOC_VIEW_CONFIDENTIAL, PERMISSIONS.DOC_UPLOAD,
    PERMISSIONS.CON_VIEW, PERMISSIONS.CON_EDIT,
    PERMISSIONS.MTG_VIEW, PERMISSIONS.MTG_EDIT,
    PERMISSIONS.RSK_VIEW, PERMISSIONS.RSK_EDIT,
    PERMISSIONS.AUDIT_VIEW, PERMISSIONS.EXPORT,
  ],
  PROJECT_MANAGER: [
    PERMISSIONS.CO_VIEW, PERMISSIONS.CO_CREATE, PERMISSIONS.CO_EDIT, PERMISSIONS.CO_SUBMIT,
    PERMISSIONS.CR_VIEW, PERMISSIONS.CR_TRIAGE, PERMISSIONS.CR_ASSIGN, PERMISSIONS.CR_COMPLETE,
    PERMISSIONS.FIN_VIEW, PERMISSIONS.FIN_EDIT_BUDGET,
    PERMISSIONS.SCH_VIEW, PERMISSIONS.SCH_EDIT,
    PERMISSIONS.LOG_VIEW, PERMISSIONS.LOG_EDIT,
    PERMISSIONS.INV_VIEW, PERMISSIONS.INV_EDIT,
    PERMISSIONS.DRW_VIEW, PERMISSIONS.DRW_UPLOAD,
    PERMISSIONS.DOC_VIEW, PERMISSIONS.DOC_UPLOAD,
    PERMISSIONS.CON_VIEW, PERMISSIONS.CON_EDIT,
    PERMISSIONS.MTG_VIEW, PERMISSIONS.MTG_EDIT,
    PERMISSIONS.RSK_VIEW, PERMISSIONS.RSK_EDIT,
    PERMISSIONS.AUDIT_VIEW, PERMISSIONS.EXPORT,
  ],
  CAPTAIN: [
    PERMISSIONS.CO_VIEW, PERMISSIONS.CO_CREATE, PERMISSIONS.CO_APPROVE_CAPTAIN,
    PERMISSIONS.CR_VIEW, PERMISSIONS.CR_TRIAGE, PERMISSIONS.CR_ASSIGN, PERMISSIONS.CR_COMPLETE,
    PERMISSIONS.FIN_VIEW, PERMISSIONS.SCH_VIEW, PERMISSIONS.LOG_VIEW,
    PERMISSIONS.INV_VIEW, PERMISSIONS.INV_EDIT,
    PERMISSIONS.DRW_VIEW, PERMISSIONS.DOC_VIEW, PERMISSIONS.CON_VIEW,
    PERMISSIONS.MTG_VIEW, PERMISSIONS.MTG_EDIT, PERMISSIONS.RSK_VIEW, PERMISSIONS.RSK_EDIT,
  ],
  CHIEF_OFFICER: [
    PERMISSIONS.CO_VIEW, PERMISSIONS.CR_VIEW, PERMISSIONS.CR_CREATE, PERMISSIONS.CR_TRIAGE,
    PERMISSIONS.CR_ASSIGN, PERMISSIONS.SCH_VIEW, PERMISSIONS.LOG_VIEW,
    PERMISSIONS.INV_VIEW, PERMISSIONS.INV_EDIT, PERMISSIONS.DOC_VIEW, PERMISSIONS.MTG_VIEW,
  ],
  CHIEF_ENGINEER: [
    PERMISSIONS.CO_VIEW, PERMISSIONS.CO_CREATE, PERMISSIONS.CR_VIEW, PERMISSIONS.CR_CREATE,
    PERMISSIONS.CR_TRIAGE, PERMISSIONS.CR_ASSIGN, PERMISSIONS.CR_COMPLETE,
    PERMISSIONS.SCH_VIEW, PERMISSIONS.INV_VIEW, PERMISSIONS.INV_EDIT,
    PERMISSIONS.DRW_VIEW, PERMISSIONS.DOC_VIEW, PERMISSIONS.MTG_VIEW, PERMISSIONS.RSK_VIEW,
  ],
  PURSER: [
    PERMISSIONS.CR_VIEW, PERMISSIONS.CR_CREATE, PERMISSIONS.CR_TRIAGE,
    PERMISSIONS.FIN_VIEW, PERMISSIONS.LOG_VIEW, PERMISSIONS.LOG_EDIT,
    PERMISSIONS.DOC_VIEW, PERMISSIONS.DOC_UPLOAD, PERMISSIONS.MTG_VIEW,
  ],
  HOD: [
    PERMISSIONS.CO_VIEW, PERMISSIONS.CR_VIEW, PERMISSIONS.CR_CREATE, PERMISSIONS.CR_TRIAGE,
    PERMISSIONS.CR_ASSIGN, PERMISSIONS.CR_COMPLETE, PERMISSIONS.SCH_VIEW,
    PERMISSIONS.INV_VIEW, PERMISSIONS.INV_EDIT, PERMISSIONS.DOC_VIEW, PERMISSIONS.MTG_VIEW,
  ],
  CREW: [PERMISSIONS.CR_VIEW, PERMISSIONS.CR_CREATE, PERMISSIONS.SCH_VIEW, PERMISSIONS.MTG_VIEW],
  YARD_PM: [
    PERMISSIONS.CO_VIEW, PERMISSIONS.CO_APPROVE_YARD,
    PERMISSIONS.SCH_VIEW, PERMISSIONS.SCH_EDIT, PERMISSIONS.LOG_VIEW, PERMISSIONS.LOG_EDIT,
    PERMISSIONS.CON_VIEW, PERMISSIONS.CON_EDIT, PERMISSIONS.DRW_VIEW, PERMISSIONS.MTG_VIEW,
  ],
  YARD_TRADE_LEAD: [PERMISSIONS.CO_VIEW, PERMISSIONS.SCH_VIEW, PERMISSIONS.LOG_VIEW, PERMISSIONS.DRW_VIEW],
  CONTRACTOR: [PERMISSIONS.CO_VIEW, PERMISSIONS.SCH_VIEW, PERMISSIONS.DOC_VIEW],
  SUPPLIER: [PERMISSIONS.DOC_VIEW],
  FINANCE: [
    PERMISSIONS.CO_VIEW, PERMISSIONS.CO_APPROVE_FINANCE,
    PERMISSIONS.FIN_VIEW, PERMISSIONS.FIN_EDIT_BUDGET, PERMISSIONS.FIN_APPROVE,
    PERMISSIONS.DOC_VIEW, PERMISSIONS.DOC_VIEW_CONFIDENTIAL, PERMISSIONS.EXPORT,
  ],
  TECH_MANAGER: [
    PERMISSIONS.CO_VIEW, PERMISSIONS.CO_APPROVE_TECH,
    PERMISSIONS.SCH_VIEW, PERMISSIONS.DRW_VIEW, PERMISSIONS.DRW_APPROVE,
    PERMISSIONS.DOC_VIEW, PERMISSIONS.RSK_VIEW, PERMISSIONS.RSK_EDIT,
  ],
  CLASS_SURVEYOR: [PERMISSIONS.CO_VIEW, PERMISSIONS.CO_APPROVE_CLASS, PERMISSIONS.DRW_VIEW, PERMISSIONS.DOC_VIEW],
  FLAG_SURVEYOR: [PERMISSIONS.CO_VIEW, PERMISSIONS.CO_APPROVE_FLAG, PERMISSIONS.DRW_VIEW, PERMISSIONS.DOC_VIEW],
  AUDITOR: [
    PERMISSIONS.CO_VIEW, PERMISSIONS.CR_VIEW, PERMISSIONS.FIN_VIEW, PERMISSIONS.SCH_VIEW,
    PERMISSIONS.LOG_VIEW, PERMISSIONS.INV_VIEW, PERMISSIONS.DRW_VIEW, PERMISSIONS.DOC_VIEW,
    PERMISSIONS.CON_VIEW, PERMISSIONS.MTG_VIEW, PERMISSIONS.RSK_VIEW, PERMISSIONS.AUDIT_VIEW,
  ],
  GUEST: [PERMISSIONS.CO_VIEW, PERMISSIONS.SCH_VIEW],
};

export function hasPermission(user: NonNullable<CurrentUser>, perm: PermissionKey): boolean {
  return user.permissions.has(perm);
}

export function hasAnyRole(user: NonNullable<CurrentUser>, ...roles: RoleKey[]): boolean {
  return roles.some((r) => user.roleKeys.includes(r));
}

export function assertPermission(user: NonNullable<CurrentUser>, perm: PermissionKey) {
  if (!hasPermission(user, perm)) {
    throw new Error(`Forbidden: missing ${perm}`);
  }
}
