import type { CurrentUser } from "./auth";
import type { RoleKey } from "./enums";
import { forbidden } from "./errors";

// Permission keys used across the app. Format: <resource>.<action>[.<qualifier>]
export const PERMISSIONS = {
  // change orders
  CO_VIEW: "change_order.view",
  CO_CREATE: "change_order.create",
  CO_EDIT: "change_order.edit",
  CO_SUBMIT: "change_order.submit",
  CO_APPROVE_CAPTAIN: "change_order.approve.captain",
  CO_APPROVE_OWNERS_REP: "change_order.approve.owners_rep",
  CO_APPROVE_YARD: "change_order.approve.yard",
  CO_APPROVE_FINANCE: "change_order.approve.finance",
  CO_APPROVE_TECH: "change_order.approve.tech_manager",
  CO_APPROVE_CLASS: "change_order.approve.class",
  CO_APPROVE_FLAG: "change_order.approve.flag",
  CO_CANCEL: "change_order.cancel",
  // crew requests
  CR_VIEW: "crew_request.view",
  CR_CREATE: "crew_request.create",
  CR_TRIAGE: "crew_request.triage",
  CR_ASSIGN: "crew_request.assign",
  CR_COMPLETE: "crew_request.complete",
  // financials
  FIN_VIEW: "financial.view",
  // schedule
  SCH_VIEW: "schedule.view",
  // logistics
  LOG_VIEW: "logistics.view",
  // inventory
  INV_VIEW: "inventory.view",
  // drawings
  DRW_VIEW: "drawing.view",
  // documents
  DOC_VIEW: "document.view",
  DOC_VIEW_CONFIDENTIAL: "document.view.confidential",
  // contractors
  CON_VIEW: "contractor.view",
  // meetings
  MTG_VIEW: "meeting.view",
  // risks
  RSK_VIEW: "risk.view",
  // projects
  PROJ_EDIT: "project.edit",
  // jobs & quotes — the yard portal's core object
  JOB_VIEW: "job.view",
  JOB_REQUEST: "job.request",
  JOB_ISSUE_QUOTE: "job.issue_quote",
  JOB_ACCEPT: "job.accept",
  JOB_COUNTERSIGN: "job.countersign",
  JOB_CANCEL: "job.cancel",
  JOB_PROGRESS: "job.progress",
  JOB_COMPLETE: "job.complete",
  JOB_WORKS_ACCEPT: "job.works_accept",
  JOB_DEFICIENCY: "job.deficiency",
  JOB_COMMENT: "job.comment",
  MINUTES_RECORD: "minutes.record",
  // admin
  ADM_USERS: "admin.users",
  AUDIT_VIEW: "audit.view",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Role -> default permission set. Keep this single matrix as the seed.
export const ROLE_PERMISSIONS: Record<RoleKey, PermissionKey[]> = {
  OWNER: [
    PERMISSIONS.JOB_VIEW,
    PERMISSIONS.CO_VIEW, PERMISSIONS.CR_VIEW, PERMISSIONS.FIN_VIEW,
    PERMISSIONS.SCH_VIEW, PERMISSIONS.LOG_VIEW, PERMISSIONS.INV_VIEW,
    PERMISSIONS.DRW_VIEW, PERMISSIONS.DOC_VIEW, PERMISSIONS.DOC_VIEW_CONFIDENTIAL,
    PERMISSIONS.CON_VIEW, PERMISSIONS.MTG_VIEW, PERMISSIONS.RSK_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
  OWNERS_REP: [
    PERMISSIONS.PROJ_EDIT,
    PERMISSIONS.JOB_VIEW, PERMISSIONS.JOB_REQUEST, PERMISSIONS.JOB_ACCEPT,
    PERMISSIONS.JOB_CANCEL, PERMISSIONS.JOB_WORKS_ACCEPT, PERMISSIONS.JOB_DEFICIENCY,
    PERMISSIONS.JOB_COMMENT, PERMISSIONS.MINUTES_RECORD,
    PERMISSIONS.CO_VIEW, PERMISSIONS.CO_CREATE, PERMISSIONS.CO_EDIT, PERMISSIONS.CO_SUBMIT,
    PERMISSIONS.CO_APPROVE_OWNERS_REP, PERMISSIONS.CO_CANCEL,
    PERMISSIONS.CR_VIEW, PERMISSIONS.CR_TRIAGE, PERMISSIONS.CR_ASSIGN,
    PERMISSIONS.FIN_VIEW,
    PERMISSIONS.SCH_VIEW,
    PERMISSIONS.LOG_VIEW,
    PERMISSIONS.INV_VIEW, PERMISSIONS.DRW_VIEW,
    PERMISSIONS.DOC_VIEW, PERMISSIONS.DOC_VIEW_CONFIDENTIAL,
    PERMISSIONS.CON_VIEW,
    PERMISSIONS.MTG_VIEW,
    PERMISSIONS.RSK_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
  PROJECT_MANAGER: [
    PERMISSIONS.PROJ_EDIT,
    PERMISSIONS.JOB_VIEW, PERMISSIONS.JOB_REQUEST, PERMISSIONS.JOB_ACCEPT,
    PERMISSIONS.JOB_CANCEL, PERMISSIONS.JOB_WORKS_ACCEPT, PERMISSIONS.JOB_DEFICIENCY,
    PERMISSIONS.JOB_COMMENT, PERMISSIONS.MINUTES_RECORD,
    PERMISSIONS.CO_VIEW, PERMISSIONS.CO_CREATE, PERMISSIONS.CO_EDIT, PERMISSIONS.CO_SUBMIT,
    PERMISSIONS.CR_VIEW, PERMISSIONS.CR_TRIAGE, PERMISSIONS.CR_ASSIGN, PERMISSIONS.CR_COMPLETE,
    PERMISSIONS.FIN_VIEW,
    PERMISSIONS.SCH_VIEW,
    PERMISSIONS.LOG_VIEW,
    PERMISSIONS.INV_VIEW,
    PERMISSIONS.DRW_VIEW,
    PERMISSIONS.DOC_VIEW,
    PERMISSIONS.CON_VIEW,
    PERMISSIONS.MTG_VIEW,
    PERMISSIONS.RSK_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
  CAPTAIN: [
    PERMISSIONS.JOB_VIEW, PERMISSIONS.JOB_REQUEST, PERMISSIONS.JOB_ACCEPT,
    PERMISSIONS.JOB_CANCEL, PERMISSIONS.JOB_WORKS_ACCEPT, PERMISSIONS.JOB_DEFICIENCY,
    PERMISSIONS.JOB_COMMENT, PERMISSIONS.MINUTES_RECORD,
    PERMISSIONS.CO_VIEW, PERMISSIONS.CO_CREATE, PERMISSIONS.CO_APPROVE_CAPTAIN,
    PERMISSIONS.CR_VIEW, PERMISSIONS.CR_TRIAGE, PERMISSIONS.CR_ASSIGN, PERMISSIONS.CR_COMPLETE,
    PERMISSIONS.FIN_VIEW, PERMISSIONS.SCH_VIEW, PERMISSIONS.LOG_VIEW,
    PERMISSIONS.INV_VIEW,
    PERMISSIONS.DRW_VIEW, PERMISSIONS.DOC_VIEW, PERMISSIONS.CON_VIEW,
    PERMISSIONS.MTG_VIEW, PERMISSIONS.RSK_VIEW,
  ],
  CHIEF_OFFICER: [
    PERMISSIONS.JOB_VIEW, PERMISSIONS.JOB_REQUEST, PERMISSIONS.JOB_COMMENT,
    PERMISSIONS.CO_VIEW, PERMISSIONS.CR_VIEW, PERMISSIONS.CR_CREATE, PERMISSIONS.CR_TRIAGE,
    PERMISSIONS.CR_ASSIGN, PERMISSIONS.SCH_VIEW, PERMISSIONS.LOG_VIEW,
    PERMISSIONS.INV_VIEW, PERMISSIONS.DOC_VIEW, PERMISSIONS.MTG_VIEW,
  ],
  CHIEF_ENGINEER: [
    PERMISSIONS.JOB_VIEW, PERMISSIONS.JOB_REQUEST, PERMISSIONS.JOB_COMMENT,
    PERMISSIONS.CO_VIEW, PERMISSIONS.CO_CREATE, PERMISSIONS.CR_VIEW, PERMISSIONS.CR_CREATE,
    PERMISSIONS.CR_TRIAGE, PERMISSIONS.CR_ASSIGN, PERMISSIONS.CR_COMPLETE,
    PERMISSIONS.SCH_VIEW, PERMISSIONS.INV_VIEW,
    PERMISSIONS.DRW_VIEW, PERMISSIONS.DOC_VIEW, PERMISSIONS.MTG_VIEW, PERMISSIONS.RSK_VIEW,
  ],
  PURSER: [
    PERMISSIONS.CR_VIEW, PERMISSIONS.CR_CREATE, PERMISSIONS.CR_TRIAGE,
    PERMISSIONS.FIN_VIEW, PERMISSIONS.LOG_VIEW,
    PERMISSIONS.DOC_VIEW, PERMISSIONS.MTG_VIEW,
  ],
  HOD: [
    PERMISSIONS.JOB_VIEW, PERMISSIONS.JOB_REQUEST, PERMISSIONS.JOB_COMMENT,
    PERMISSIONS.CO_VIEW, PERMISSIONS.CR_VIEW, PERMISSIONS.CR_CREATE, PERMISSIONS.CR_TRIAGE,
    PERMISSIONS.CR_ASSIGN, PERMISSIONS.CR_COMPLETE, PERMISSIONS.SCH_VIEW,
    PERMISSIONS.INV_VIEW, PERMISSIONS.DOC_VIEW, PERMISSIONS.MTG_VIEW,
  ],
  CREW: [
    PERMISSIONS.JOB_VIEW, PERMISSIONS.JOB_REQUEST,
    PERMISSIONS.CR_VIEW, PERMISSIONS.CR_CREATE, PERMISSIONS.SCH_VIEW, PERMISSIONS.MTG_VIEW,
  ],
  YARD_PM: [
    PERMISSIONS.JOB_VIEW, PERMISSIONS.JOB_ISSUE_QUOTE, PERMISSIONS.JOB_COUNTERSIGN,
    PERMISSIONS.JOB_CANCEL, PERMISSIONS.JOB_PROGRESS, PERMISSIONS.JOB_COMPLETE,
    PERMISSIONS.JOB_COMMENT, PERMISSIONS.MINUTES_RECORD,
    PERMISSIONS.CO_VIEW, PERMISSIONS.CO_APPROVE_YARD,
    PERMISSIONS.SCH_VIEW, PERMISSIONS.LOG_VIEW,
    PERMISSIONS.CON_VIEW, PERMISSIONS.DRW_VIEW, PERMISSIONS.MTG_VIEW,
  ],
  YARD_TRADE_LEAD: [PERMISSIONS.JOB_VIEW, PERMISSIONS.JOB_PROGRESS, PERMISSIONS.JOB_COMMENT, PERMISSIONS.CO_VIEW, PERMISSIONS.SCH_VIEW, PERMISSIONS.LOG_VIEW, PERMISSIONS.DRW_VIEW],
  CONTRACTOR: [PERMISSIONS.JOB_VIEW, PERMISSIONS.CO_VIEW, PERMISSIONS.SCH_VIEW, PERMISSIONS.DOC_VIEW],
  SUPPLIER: [PERMISSIONS.DOC_VIEW],
  FINANCE: [
    PERMISSIONS.JOB_VIEW,
    PERMISSIONS.CO_VIEW, PERMISSIONS.CO_APPROVE_FINANCE,
    PERMISSIONS.FIN_VIEW,
    PERMISSIONS.DOC_VIEW, PERMISSIONS.DOC_VIEW_CONFIDENTIAL,
  ],
  TECH_MANAGER: [
    PERMISSIONS.JOB_VIEW, PERMISSIONS.JOB_COMMENT,
    PERMISSIONS.CO_VIEW, PERMISSIONS.CO_APPROVE_TECH,
    PERMISSIONS.SCH_VIEW, PERMISSIONS.DRW_VIEW,
    PERMISSIONS.DOC_VIEW, PERMISSIONS.RSK_VIEW,
  ],
  CLASS_SURVEYOR: [PERMISSIONS.CO_VIEW, PERMISSIONS.CO_APPROVE_CLASS, PERMISSIONS.DRW_VIEW, PERMISSIONS.DOC_VIEW],
  FLAG_SURVEYOR: [PERMISSIONS.CO_VIEW, PERMISSIONS.CO_APPROVE_FLAG, PERMISSIONS.DRW_VIEW, PERMISSIONS.DOC_VIEW],
  AUDITOR: [
    PERMISSIONS.JOB_VIEW,
    PERMISSIONS.CO_VIEW, PERMISSIONS.CR_VIEW, PERMISSIONS.FIN_VIEW, PERMISSIONS.SCH_VIEW,
    PERMISSIONS.LOG_VIEW, PERMISSIONS.INV_VIEW, PERMISSIONS.DRW_VIEW, PERMISSIONS.DOC_VIEW,
    PERMISSIONS.CON_VIEW, PERMISSIONS.MTG_VIEW, PERMISSIONS.RSK_VIEW, PERMISSIONS.AUDIT_VIEW,
  ],
  GUEST: [PERMISSIONS.CO_VIEW, PERMISSIONS.SCH_VIEW],
};

export function hasPermission(user: NonNullable<CurrentUser>, perm: PermissionKey): boolean {
  return user.permissions.has(perm);
}

export function hasAnyRole(user: NonNullable<CurrentUser>, ...roles: RoleKey[]): boolean {
  return roles.some((r) => user.roleKeys.includes(r));
}

/**
 * Refuse unless the user holds the permission.
 *
 * The thrown `ActionError` reaches the browser, so it says what the user may
 * not do, not which permission key they are missing — naming the key tells an
 * attacker the shape of the permission model. The key is still in the logs via
 * the digest.
 */
export function assertPermission(user: NonNullable<CurrentUser>, perm: PermissionKey) {
  if (!hasPermission(user, perm)) {
    throw forbidden("You do not have permission to do that.");
  }
}
